pgp_agent_dropout_augmentation:
  _target_: tuplan_garage.planning.training.data_augmentation.pgp.pgp_agent_dropout_augmentation.PGPAgentDropoutAugmentor
  _convert_: 'all'

  augment_prob: 0.5  # probability of applying data augmentation for training
  dropout_rate: 0.5  # probability of an agent being dropout
