pdm_hybrid_planner:
  _target_: tuplan_garage.planning.simulation.planner.pdm_planner.pdm_hybrid_planner.PDMHybridPlanner
  _convert_: 'all'

  # parameters for output trajectory
  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 80 # target future poses
    interval_length: 0.1 # interval of samples [s]

  # parameters for proposals
  proposal_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 40 # target future poses
    interval_length: 0.1 # interval of samples [s]

  idm_policies:
    _target_: tuplan_garage.planning.simulation.planner.pdm_planner.proposal.batch_idm_policy.BatchIDMPolicy
    _convert_: 'all'
    speed_limit_fraction: [0.2,0.4,0.6,0.8,1.0] # Target velocity as fractions of current speed-limit
    fallback_target_velocity: 15.0 # Desired fallback velocity in free traffic [m/s]
    min_gap_to_lead_agent: 1.0 # Minimum relative distance to lead vehicle [m]
    headway_time: 1.5 # Desired time headway. The minimum possible time to the vehicle in front [s]
    accel_max: 1.5 # Maximum acceleration [m/s^2]
    decel_max: 3.0 # Maximum deceleration (positive value) [m/s^2]

  lateral_offsets: [-1.0, 1.0] # Signed offsets from centerline (or null) [m]
  map_radius: 50 # Radius to consider around ego [m]

  model:
    _target_: tuplan_garage.planning.training.modeling.models.pdm_offset_model.PDMOffsetModel
    _convert_: 'all'

    trajectory_sampling:
      _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
      _convert_: 'all'
      num_poses: 16      # target future poses
      interval_length: 0.5

    history_sampling:
      _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
      _convert_: 'all'
      num_poses: 10      # target future poses
      interval_length: 0.2

    planner: null
    centerline_samples: 120 # number of samples poses on centerline
    centerline_interval: 1.0  #  interval of sampled poses on centerline [m]
    hidden_dim: 512

  correction_horizon: 2.0 # time after which correction is applied (parameter C) [s]
  checkpoint_path: ???
